### ISSUE TITLE
online Demo

### ISSUE THREAD

**Issue by iakRulan** [OpenRobotLab/PointLLM#10]
Hello author, I have been unable to load the online demo website. Could you tell me the approximate loading time? Thank you！
![image](https://github.com/OpenRobotLab/PointLLM/assets/88355032/c2a864e5-cd8e-4eef-9b9e-7936fbef787e)

**Comment by iakRulan** [comment]
I just discovered that it's due to "502 Bad Gateway", What should I do?
![image](https://github.com/OpenRobotLab/PointLLM/assets/88355032/40662205-8a7e-492e-8268-dcbbdb20604a)

**Comment by RunsenXu** [comment]
The server is currently down, I am fixing it. Sorry about that.

**Comment by RunsenXu** [comment]
It's working now. Thanks.

**Comment by iakRulan** [comment]
Thank you for your help!
