### ISSUE TITLE
online Demo is failed

### ISSUE THREAD

**Issue by wuxiaofei01** [OpenRobotLab/PointLLM#11]
Hello author, thank you very much for your work, but when I tried to open the demo, I found that **the web page could not be accessed.**
![image](https://github.com/OpenRobotLab/PointLLM/assets/61744147/74904364-0311-4650-b845-550b523c2e18)

**Comment by RunsenXu** [comment]
Hi,

Thank you for your interest. It seems the online demo is functioning well for me. Could you check your network or try http://101.230.144.196/

Best,
Runsen
