### ISSUE TITLE
NO File  ModelNet

### ISSUE THREAD

**Issue by TangYuan96** [OpenRobotLab/PointLLM#14]
First, thanks for sharing so outstanding work!

There is no file   `ModelNet`  in   `PointLLM/pointllm/data`.

<img width="463" alt="1704272125127" src="https://github.com/OpenRobotLab/PointLLM/assets/28919555/9118ac1f-8394-427c-8bfa-3d53c944dd16">

**Comment by RunsenXu** [comment]
Hi, thanks for pointing out this. 

The .gitignore file has something wrong so I miss these important files. Now they should work and you may pull the latest commit.

**Comment by TangYuan96** [comment]
Thanks for your quick response.   It now works.
