### ISSUE TITLE
too long time for inference demo

### ISSUE THREAD

**Issue by jkstyle2** [OpenRobotLab/PointLLM#16]
Is it normal to take time around 20~30 mins for 6MB pointcloud data during inference?
or should I make the input into data a simpler&optimized format for the demo?

![image](https://github.com/OpenRobotLab/PointLLM/assets/34189274/8aceac35-7173-4da5-a527-e406220f1278)

**Comment by RunsenXu** [comment]
Hi,

How many points are there in your data? Downsample to 8192 points using FPS sampling or random sampling and try again. 20-30 mins are too long. Usually it should take dozens of seconds.

**Comment by jkstyle2** [comment]
It was originally 450k. and Now it works fast enough after sampling the points to 20k. Thanks a lot!
