### ISSUE TITLE
Ask for pre-trained models

### ISSUE THREAD

**Issue by Zscozer** [OpenRobotLab/PointLLM#2]
Hi, great job! Do you have plan to release the weights for the PointLLM model, or provide an open source API?

**Comment by RunsenXu** [comment]
Yes, I am trying to release the inference code with the pre-trained models in this week.

**Comment by RunsenXu** [comment]
Dear @Zscozer,

I have released the inference codes with the model weights. Please check out the README.

Best,
Runsen
