### ISSUE TITLE
Scene Understanding

### ISSUE THREAD

**Issue by LilRedWu** [OpenRobotLab/PointLLM#20]
Thanks for your excellent job!  In the paper，you mentioned the pointLLM scence and showed its capability of scene understanding. I am wondering which checkpoints correspond to the scene model?

**Comment by RunsenXu** [comment]
Hi, which parts of the paper are you mentioning? We haven't released the scene model at the moment and all experiments in the paper are based on object point clouds (though these models can accept scene-level point clouds and generate outputs).
