### ISSUE TITLE
How to inference with Colorless Point Cloud

### ISSUE THREAD

**Issue by Calmepro777** [OpenRobotLab/PointLLM#22]
Hello,

Thanks for the authors' fantanstic work shared here.

I wonder how to  inference with colorless point cloud. 

The model I am using is the pretrained PointLLM_13B_v1.2.

Here are some failed attempt I had:

- Feed the model with 3-dim pointcloud --> model does not accept
- Set "use_color" in the config file of the model --> falied to load checkpoint

Thanks in advance.

**Comment by RunsenXu** [comment]
Hi, the released models only accept colored point clouds. If you need to use colorless point clouds, you need to modify the model architecture (the dimension of the point cloud encoder). I recommend appending [0, 0, 0] or [1, 1, 1] to your point cloud, which means your point clouds are all with black color or white color so the model can accept them.

**Comment by Calmepro777** [comment]
> Hi, the released models only accept colored point clouds. If you need to use colorless point clouds, you need to modify the model architecture (the dimension of the point cloud encoder). I recommend appending [0, 0, 0] or [1, 1, 1] to your point cloud, which means your point clouds are all with black color or white color so the model can accept them.

Thank you for your prompt reply.

Does it mean that modifying the model arch requires retraining of the model.

**Comment by RunsenXu** [comment]
Yes. You should retrain the point cloud encoder and retrain PointLLM.
