### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Qifeng-Wu99** [OpenRobotLab/PointLLM#25]
Hello,

Thanks for the fantastic work.

I would like to know how the the dataset containing uniformly sampled points is created.

I took a look at the mesh objects in objaverse and noticed that the mesh was not uniformly distributed, meaning that if we only sample the vertices of the meshes to point clouds, the point clouds will also be non-uniform.

I will appreciated if authors could show me some related instructions, code scripts, etc. 

Thanks in advance

**Comment by RunsenXu** [comment]
Hi, you may refer to https://github.com/crockwell/Cap3D/ for the point cloud generation, which I believe uses codes from Point-E. We use the point cloud generated from Cap3D.

**Comment by RunsenXu** [comment]
Hi, is there anything I can help with?
