### ISSUE TITLE
PointBERT re-training Code

### ISSUE THREAD

**Issue by fattho0919** [OpenRobotLab/PointLLM#26]
Hello,

Thanks for the fantastic work.

I want to re-train the PointBERT in scene level,
you mention that you re-train the PointBERT with color information
so could you please provide the pretraining code to me,
thanks a lot!!!

**Comment by RunsenXu** [comment]
Hi,
Thanks for your interest in our work. You may refer to the original ULIP-2 codebase.

**Comment by KzZheng** [comment]
Hi Runsen @RunsenXu,

Do you know the features of your PointBERT aligns with which open-clip model? In the ULIP-2 paper, they mentioned using 'ViT-g-14', but its feature dimension is 1024, which does not match with 768 in the PointBERT. I wonder whether you know the answer. Thanks!

Best,
Kz

**Comment by RunsenXu** [comment]
OpenCLIP ViT-L/14, datacomp xl s13b b90
