### ISSUE TITLE
More Checkpoints

### ISSUE THREAD

**Issue by MathewCrespo** [OpenRobotLab/PointLLM#29]
Hi, thanks for your great work!

I am currently looking into the training phase of the PointLLM. I am wondering if you can release the checkpoints of the weights after Stage1 (the pre-trained weights before stage2). I have checked Hugging Face repo, and only found the final V1.2 ckpt.

I would appreciate it if you could release more ckpts!

**Comment by RunsenXu** [comment]
The checkpoints need some cleaning and uploading, let me try if I can release them recently.

**Comment by MathewCrespo** [comment]
> The checkpoints need some cleaning and uploading, let me try if I can release them recently.

Thanks for ur in-time reply！

**Comment by RunsenXu** [comment]
Hi,

I found that the stage 1 checkpoints have already been deleted. Sorry about that. Do you have any difficulty in retraining the model by yourself?

Best,
Runsen

**Comment by RunsenXu** [comment]
I will close this issue. Feel free to reopen it if you have any problem reproducing the stage 1 checkpoints.

**Comment by MathewCrespo** [comment]
> Hi,
> 
> I found that the stage 1 checkpoints have already been deleted. Sorry about that. Do you have any difficulty in retraining the model by yourself?
> 
> Best, Runsen

Thank you for the reply! Now I am trying to train the PointLLM with my own customized instruction dataset. I think I can directly tune the model upon the ckpt of stage2.
