### ISSUE TITLE
Use my own data locally

### ISSUE THREAD

**Issue by taoranyi** [OpenRobotLab/PointLLM#3]
Great work! I want to know how to use my own data locally, especially in the aspect of point cloud and text alignment.

**Comment by RunsenXu** [comment]
Hi, 
I will open source the training codes one month later. Please stay tuned.
Best,
Runsen

**Comment by QvQKing** [comment]
> Hi, I will open source the training codes one month later. Please stay tuned. Best, Runsen

Hello, will you release training code soon

**Comment by RunsenXu** [comment]
Dear QvQKing,

I have been occupied by CVPR 2024 DDL recently, so I am afraid I cannot clean my codes on time. Could you send me an email so I can share my uncleaned codes for the dataset and trainer, if you want?

Best,
Runsen

**Comment by QvQKing** [comment]
> Dear QvQKing,
> 
> I have been occupied by CVPR 2024 DDL recently, so I am afraid I cannot clean my codes on time. Could you send me an email so I can share my uncleaned codes for the dataset and trainer, if you want?
> 
> Best, Runsen

Thanks! My email is 1214615379@qq.com.

**Comment by LinfengUP** [comment]
> Dear QvQKing,
> 
> I have been occupied by CVPR 2024 DDL recently, so I am afraid I cannot clean my codes on time. Could you send me an email so I can share my uncleaned codes for the dataset and trainer, if you want?
> 
> Best, Runsen

Hi Runsen, 
If possible, I also want to get the uncleaned codes. My email is linfeng.up@gmail.com. Thanks!

**Comment by gunny97** [comment]
Hi Runsen,
If possible, can I get the uncleaned codes? My email is keonwookim@vrcrew.com.
Thanks!
