### ISSUE TITLE
point number of the point cloud

### ISSUE THREAD

**Issue by zhouzhouha** [OpenRobotLab/PointLLM#30]
is this correct: all the point clouds more than 8192 points will be downsampled to 8192, if less than 8192 points the system will do nothing?
The second question is can PointLLM support any number of points in the future?

**Comment by RunsenXu** [comment]
Hi,

1. Yes. Please refer to https://github.com/OpenRobotLab/PointLLM/blob/ecad205a84b2c2070ab875a76353a695c6fa6236/pointllm/eval/chat_gradio.py#L170

2. Inputting any number of points is supported now, though our model was trained with point clouds of 8192 points.
