### ISSUE TITLE
CUDA_OUT_OF_MEMORY & Some weights of PointLLMLlamaForCausalLM were not initialized

### ISSUE THREAD

**Issue by bearthesilly** [OpenRobotLab/PointLLM#32]
Thanks for your fantastic work on combining the llm and point cloud together!
When begin training stage 1, I met two issues:
First, I run training on four RTX3090 with 24GB memory each. Though setting the batchsize to 1, the CUDA OUT OF MEMORY occurs. Is there any solution to this? 
Secondly, an info of stderr says: "Some weights of PointLLMLlamaForCausalLM were not initialized from the model checkpoint at checkpoints/PointLLM_7B_v1.1_init and are newly initialized". The detailed picture is attached below. I prepared the checkpoints/PointLLM_7B_v1.1_init according to the instruction, and don't know how to solve the problem. 
<img width="1683" alt="屏幕截图 2024-07-12 204129" src="https://github.com/user-attachments/assets/f38b3819-ee87-42c9-ab6f-cfcb1a5d6dcf">
Again, thanks for your contribution to the community! Looking forward to your reply~

Best, 
Sillybear

**Comment by RunsenXu** [comment]
Hi,

For the first question, please refer to: https://github.com/OpenRobotLab/PointLLM/issues/31#issuecomment-2225949468

For the second question, that std-error message is normal, just disregard it. For stage-1 training, the weights of the point encoder will be separate loaded. 

<img width="1735" alt="image" src="https://github.com/user-attachments/assets/5fa463c6-9654-4836-92a8-43a3bc216385">

**Comment by bearthesilly** [comment]
Thanks for your quick reply!
Your response really helps a lot!

**Comment by bearthesilly** [comment]
Sorry to interrupt you again. I've noticed the GPU requirement for training listed in the README.md, as is shown below:
<img width="988" alt="屏幕截图 2024-07-13 185438" src="https://github.com/user-attachments/assets/d1a170d8-7637-4d59-909c-661587b470f0">
I'm still curious about why my attempt on training with LLAMA7B and torch.float16 will cause the memory issue, as 14GB(presented in the list) is way smaller than 24GB. Is it because of the huge size of the dataset or something? 
Sorry that my question may seem to be silly, for i'm still a rookie in the community. I will appreciate for your reply!

Best, 
Sillybear

**Comment by bearthesilly** [comment]
Hi! 

Sorry to interrupt you again. I've noticed the GPU requirement for training listed in the README.md, as is shown below:

<img width="988" alt="屏幕截图 2024-07-13 185438" src="https://github.com/user-attachments/assets/26712803-688a-403a-af3f-6f60d74ee270">

I'm still curious about why my attempt on training with LLAMA7B and torch.float16 will cause the memory issue, as 14GB(presented in the list) is way smaller than 24GB. Is it because of the huge size of the dataset or something?

I downloaded PointLLM_7B_v1.1_init and set the --bf16 to be `True`. Is setting `--bf16 true` the correct way to train with torch.float16? More information on the config of stage1 is attached below:
<img width="835" alt="屏幕截图 2024-07-13 191738" src="https://github.com/user-attachments/assets/8a56963f-02c2-4b47-a2fc-4c2ce7eaf705">

Sorry that my question may seem to be silly, for i'm still a rookie in the community. I will appreciate for your reply!

Best,
Sillybear

**Comment by RunsenXu** [comment]
Hi,

1. The GPU requirements are simply the requirements for loading the model, which should be the minimum requirements for inferencing. For training, you need at least 4x memory to store the parameters, gradient, activation, and momentum. 

2. You should set float16, because bf16 is only supported by A100 and above GPUS.

**Comment by bearthesilly** [comment]
Thanks for your quick reply!
May I ask how can I set to float16? 
Furthermore, if I want to switch the language model, e.g, LLAMA7B to t5 base model, what should I do?
Again, thank you for your patient reply~ QAQ

Best,
Sillybear

**Comment by RunsenXu** [comment]
1. Try to set replace "--bf16 True" with "--fp16 True". You can refer to https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments

2. I suggest you carefully examine the inference process of PointLLM and understand the underlying procedures. You will find that this file preprocesses the point tokens and transforms them into token sequences that can be processed by the LLM backbone. After that, it simply calls the forward function of the LLM. To switch to T5, you should identify its format, which I believe should be 95% similar.

https://github.com/OpenRobotLab/PointLLM/blob/82b5a8251c8aa3715e5c3b0a0a9b009a6f116fe3/pointllm/model/pointllm.py#L173

**Comment by bearthesilly** [comment]
Thank you~!
