### ISSUE TITLE
There are some problems with demo

### ISSUE THREAD

**Issue by F1shhhhh** [OpenRobotLab/PointLLM#33]
Thank you for your work, it's great! 

I tried your demo, and there is no problem with uploading the point cloud and the 3D file part, but there is always ERROR in the question phase, can you fix it? thank you!

**Comment by RunsenXu** [comment]
Hi,

Does your 3D file follow the format specified here?

<img width="1166" alt="image" src="https://github.com/user-attachments/assets/f17b2522-af5d-4f79-9275-59b18a15013c">


Best,
Runsen

**Comment by F1shhhhh** [comment]
Thank you for your reply. I am using the sample file you provided with the ID b4bbf2116b1a41a5a3b9d3622b07074c

![image](https://github.com/user-attachments/assets/d8b73e7d-5df6-49ef-8574-20cc31685ae0)

**Comment by RunsenXu** [comment]
But it works for me.

<img width="1556" alt="image" src="https://github.com/user-attachments/assets/845287eb-1928-47ce-8883-c1da41f9b8c3">

**Comment by F1shhhhh** [comment]
Sorry, I realized this had to be turned off the VPN, I've fixed it, thanks!

**Comment by F1shhhhh** [comment]
Sorry, I realized this had to be turned off the VPN, I've fixed it, thanks!
