### ISSUE TITLE
关于使用blender渲染

### ISSUE THREAD

**Issue by TingdeLiu** [OpenRobotLab/PointLLM#35]
根据您的文字描述数据生成说明，你们是首先使用blender渲染.gelb文件来生成8个视角的图片。但是你们最后给的数据集又是点云数据，而blender无法处理点云数据，所以我想询问你们是如何处理点云来生成多视角图像的？

**Comment by RunsenXu** [comment]
Hello,

Please refer to https://github.com/crockwell/Cap3D

**Comment by TingdeLiu** [comment]
Hello,
thank you for your reply. I have seen this link. But they can also handle .gelb format 3d data. So I would like to know how you generate text descriptions for point clouds.

**Comment by RunsenXu** [comment]
We use the text descriptions from Cap3D and they use VLMs to caption the rendered images.
