### ISSUE TITLE
Hello, I can't get into these two DEMO URLs, is it closed?

### ISSUE THREAD

**Issue by hangpengjie** [OpenRobotLab/PointLLM#37]
These two URLs:

http://101.230.144.196/
https://openxlab.org.cn/apps/detail/openxlab-app/PointLLM

**Comment by RunsenXu** [comment]
Hi, our server is currently down, so we have not been able to host the demo recently.

**Comment by RunsenXu** [comment]
Hi, the demo has been recovered. Enjoy!
