### ISSUE TITLE
Question about 3k test set

### ISSUE THREAD

**Issue by AndreAmaduzzi** [OpenRobotLab/PointLLM#38]
Hello,
Thanks for your beautiful work!
I have a question regarding the test set of 3000 examples stored in [PointLLM_brief_description_val_3000_GT.json](https://huggingface.co/datasets/RunsenXu/PointLLM/blob/main/PointLLM_brief_description_val_3000_GT.json).
I would like to know if all these language annotations have been generated by humans + GPT, as it is the case for the 200 samples test set you evaluate your method on.

Thanks,
Andrea

**Comment by RunsenXu** [comment]
Yes

**Comment by AndreAmaduzzi** [comment]
Thank you.

Andrea
