### ISSUE TITLE
Get garbled code in my own point cloud in PointLLM_chat.py

### ISSUE THREAD

**Issue by OceanSummerDay** [OpenRobotLab/PointLLM#40]
When inferring the point cloud of the training dataset, the chat can be performed normally, but the point cloud collected by myself will output garbled characters. All point clouds have been downsampled to 8192 points.
![665f5ece34356bc84e3a2df4a3bf13c](https://github.com/user-attachments/assets/6c74c8f2-95fb-4ee4-bb7c-00271a69564d)
![938a4e992b9ef40aac8fbd9c1305454](https://github.com/user-attachments/assets/9ca858c3-481d-4d85-91f1-dea7570ae042)

output garbled characters my own data

![561ec5447483b2f20b84ca6ec656a8f](https://github.com/user-attachments/assets/316f7db5-1ccd-4fcb-a85d-ad4140404690)
![9068082bc866b4beda5ac6f9d7f6387](https://github.com/user-attachments/assets/0ef49ada-fc74-44e4-83fd-dad53d1bd12b)
![3e0cee0a4184b27a2bd0de20f4c9162](https://github.com/user-attachments/assets/bc500b0d-f91b-4b12-a697-81ed35271e1c)
![7705700f02bcd4ab15c1b2ecab4ef24](https://github.com/user-attachments/assets/5f273d9c-fd9a-4895-88e0-47c34078b6e4)

**Comment by OceanSummerDay** [comment]
Sorry, I overlooked rgb (in [0, 1] range)😣 and changed it to 0~256. My mistake. You can close this issue. Your work is amazing!🥳

**Comment by RunsenXu** [comment]
Thanks for your kind words.
