### ISSUE TITLE
CUDA out of memory in stage2

### ISSUE THREAD

**Issue by OceanSummerDay** [OpenRobotLab/PointLLM#41]
My device is A40*8 46G  torch 2.1.0 cuda 122

I don't know if the out of memory is due to some kind of BUG or insufficient GPU memory.

stage1 is ok, as setting like:
model_name=/PointLLM_7B_v1.1_init
    --per_device_train_batch_size 16 \
    --bf16 True \
       --fix_llm True \
    --fix_pointnet True \
    --gradient_checkpointing True \
    --report_to wandb \
    --run_name $filename \
    --point_backbone_ckpt $point_backbone_ckpt \
    
    
But in stage 2, even     --per_device_train_batch_size 1 \ , I still get CUDA out of memory error.
![1732180879002](https://github.com/user-attachments/assets/b1c8e389-571c-4502-82d2-de6355462025)

How many gpu memory needed at least? Isn't 46gb enough? No matter a single or multiple GPUs, I still get "torch.cuda.OutOfMemoryError: CUDA out of memory"

 as setting here:
 PYTHONPATH=$dir_path:$PYTHONPATH \
torchrun --nnodes=1 --nproc_per_node=1 --master_port=$master_port pointllm/train/train_mem.py \
    --model_name_or_path $model_name_or_path \
    --data_path $data_path \
    --anno_path $anno_path \
    --output_dir $output_dir \
    --version v1 \
    --model_max_length 2048 \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --eval_steps 100 \
    --save_strategy "no" \
    --save_steps 2400 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --bf16 True \
    --fix_llm False \
    --fix_pointnet True \
    --report_to wandb \
    --run_name $filename \
    --gradient_checkpointing True \
    --stage_2 True \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --conversation_types "detailed_description" "single_round" "multi_round" \
    --use_color True

**Comment by OceanSummerDay** [comment]
It may be because --fix_llm False \ in stage 2, caused 46gb of GPU memory to be insufficient. It may be better to use lora to adjust llm in stage 2, unless you have 80gb GPU memory🤧

**Comment by RunsenXu** [comment]
Yes you are right. Try lora.

**Comment by OceanSummerDay** [comment]
Yeah, it's fine when I use lora or --fix_llm True \ in stage 2. 
Thx for your help!🥳 46gb of GPU memory is not enough in stage 2.

**Comment by RunsenXu** [comment]
Glad that it works. 🎉

**Comment by Djerry-h** [comment]
> Yeah, it's fine when I use lora or --fix_llm True \ in stage 2. Thx for your help!🥳 46gb of GPU memory is not enough in stage 2.

Have you used LoRA for fine-tuning? Could I take a look at your code for reference?
