### ISSUE TITLE
 I can't get into these two DEMO URLs

### ISSUE THREAD

**Issue by lingcco** [OpenRobotLab/PointLLM#42]

**Comment by ZhuHongZez** [comment]
This is a great job. We hope you can provide an effective demo.

**Comment by RunsenXu** [comment]
Hi,

I am sorry, due to limitation of computing resources, the demo will not be recovered for a while.

**Comment by ZhuHongZez** [comment]
Okay, okay. We express our understanding. I will try to deploy it in A6000.

**Comment by RunsenXu** [comment]
Hi,

The demo is back. Thanks for waiting.
