### ISSUE TITLE
Add special token

### ISSUE THREAD

**Issue by XIDIANPQZ** [OpenRobotLab/PointLLM#44]
https://github.com/OpenRobotLab/PointLLM/blob/e444053866e3d5d25b1aeff3652b2d3b9c12ceea/pointllm/model/pointllm.py#L345-L349

Hello, great work! I have a question about the training of embedding layer. During the training, do you keep the previous tokens unchanged or train them together? If they are kept unchanged, how is this achieved?

**Comment by RunsenXu** [comment]
For stage-1, previous tokens are unchanged and for stage-2, previous tokens are fine-tuned. To achieve this, I detatched the gradient of the previous tokens. 
https://github.com/OpenRobotLab/PointLLM/blob/e444053866e3d5d25b1aeff3652b2d3b9c12ceea/pointllm/model/pointllm.py#L155

**Comment by XIDIANPQZ** [comment]
Thank you! I understand. I wonder if the experiment proves the effectiveness of fine-tune in stage-2. Considering that the small data size compared with the original data size, the fine-tuning may not learn the good embedding.

**Comment by RunsenXu** [comment]
Hi,

Given our model is used for point-cloud-related dialogues, fine-tuning actually does not require too much data.
