### ISSUE TITLE
Training data release

### ISSUE THREAD

**Issue by LinfengUP** [OpenRobotLab/PointLLM#8]
Hi,

This is a great work, may I know when the training data will be released?

**Comment by RunsenXu** [comment]
Hi, they are already released. Thanks.

**Comment by LinfengUP** [comment]
Sorry for my typo, I am asking for the training code. May I know when the training code will be released?

**Comment by RunsenXu** [comment]
Hi LinFengUP,

I just released the training codes.

Best,
Runsen

**Comment by LinfengUP** [comment]
Thank you!
